[local]
localhost

[mongodb]
localhost

[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[catalogue]
catalogue.mahidevops.fun

[user]
user.mahidevops.fun

[cart]
cart.mahidevops.fun

[shipping]
shipping.mahidevops.fun

[payment]
payment.mahidevops.fun

[frontend]
mahidevops.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321