- name: disable nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: remove default content
  ansible.builtin.file:
    state: absent
    path: /usr/share/nginx/html/

- name: creating html folder
  ansible.builtin.file:
    state: directory
    path: /usr/share/nginx/html/

- name: download zip file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: unzip code
  ansible.builtin.unarchive:
   src: /tmp/frontend.zip
   dest: /usr/share/nginx/html/
   remote_src: yes
  
- name: remove default content
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/nginx.conf

- name: copy nginx service
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start and enable 
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
      