- name: app set up
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name: nodejs set up
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs-setup.yaml

- name: system configuration
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml